### ISSUE TITLE
missing streets in Erie, Colorado

### ISSUE THREAD

**Issue by jholmes02** [stamen/toner-carto#70]
i look for an address and stamen maps says it cannot be found. It is a known address of a government building in colorado, i know it exists. if i pan and zoom to find it instead, none of the streets are there, no wonder it can't be found..
![google map](https://user-images.githubusercontent.com/37557472/37622074-5be94fde-2b86-11e8-881d-96489e1b132e.PNG)
![stamen map](https://user-images.githubusercontent.com/37557472/37622075-5bfce0f8-2b86-11e8-9b8f-d30ca16e23de.PNG)

**Comment by almccon** [comment]
Thanks for this bug report @jholmes02.

There are two separate issues here. The first one is that the search box is broken and says your address can't be found. We know this is a problem (tracked here https://github.com/stamen/maps.stamen.com/issues/121) and we're working on a fix for it.

The second problem is the missing streets on the map (which is actually unrelated to the first problem). Our maps use a snapshot of data from [OpenStreetmap](https://github.com/stamen/maps.stamen.com/issues/121) which is a year or two old. I think that at the time we grabbed the data from OpenStreetMap, those roads in Erie, CO were missing for some reason. 

If I look at the OSM history for one of those roads, it shows that as of a few months ago, all of those roads were tagged as "living_street" instead of "residential": https://www.openstreetmap.org/way/7692192/history

"living_street" is an unusual tag, and it turns out we're not rendering it correctly. (see #59). 

I don't know when we will next do a database update and a re-rendering of our map, but when we do, this problem should fix itself.

**Comment by loganwilliams** [comment]
fixed
