### ISSUE TITLE
toner is mapping in color, not black and white

### ISSUE THREAD

**Issue by cperk** [stamen/toner-carto#79]
I love that stamen allows for maps to be shapes other than square. However, I am having trouble producing the maptype toner as shown on your website, with high contrast black and white. When I plot it it is in color (see image). Here is my code:

```
mapbox.hud <- c(-74.2, 41, -73.5, 43)
Hudson.River <- get_map(location = mapbox.hud, source = "stamen", maptype = "toner", zoom=10,crop=T)
ggmap(Hudson.River)

```
![hudson river map feb 6](https://user-images.githubusercontent.com/21315115/52389185-32dbbf80-2a60-11e9-9e4a-853244ddd772.png)

On another note, how can I control the size of city and state names? Also, is there a way to remove them?

**Comment by almccon** [comment]
@cperk hmm, it looks like you are getting Stamen's Terrain tiles instead of Toner tiles. See http://maps.stamen.com/terrain vs http://maps.stamen.com/toner.

However this is either a bug in the `ggmap` code, or an error in how you're using `ggmap`. Stamen is not the creator or maintainer of `ggmap`, so I think you should check here for more info: https://github.com/dkahle/ggmap

Also, the label sizes in Toner and Terrain are not configurable, but possibly `ggmap` would allow you to pick a different zoom level which would have differently-sized labels.
